reservations/urls.py
from django.urls import path
from .views import (
    ReservationListView,
    ReservationUserListView,
    ReservationDetailView,
    ReservationCreateView,
    ReservationDeleteView,
    )
from . import views


urlpatterns = [
    path('', ReservationListView.as_view(), name='reservation-list'),

    path(
        'reservations-user',
        ReservationUserListView.as_view(), name='reservation-user-list'
        ),

    path(
        '<int:pk>/', ReservationDetailView.as_view(), name='reservation-detail'
        ),

    path(
        'new/', ReservationCreateView.as_view(), name='reservation-create'
        ),

    path(
        '<int:pk>/delete/',
        ReservationDeleteView.as_view(), name='reservation-delete'
        ),
    path('date/', views.date_form, name='reservation-date'),
]

tennisclub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from . import views

# Handlers for custom error pages
handler404 = 'tennisclub.views.page_not_found'
handler403 = 'tennisclub.views.permission_denied'
handler400 = 'tennisclub.views.bad_request'
handler500 = 'tennisclub.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),

    path(
        'login/', auth_views.LoginView.as_view(
            template_name='users/login.html'
            ), name='login'
        ),

    path(
        'logout/', auth_views.LogoutView.as_view(
            template_name='users/logout.html'
            ), name='logout'
        ),

    path(
        'password-reset/', auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
            ), name='password_reset'
        ),

    path(
        'password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
            ), name='password_reset_done'
        ),

    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
            ), name='password_reset_confirm'
        ),

    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
            ), name='password_reset_complete'
        ),

    path('', include('website.urls')),
    path('reserve/', include('reservations.urls')),
]

website/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    )
from . import views


urlpatterns = [
    path('news', PostListView.as_view(), name='website-news'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),

    path(
        'post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'
        ),

    path(
        'post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'
        ),

    path('about', views.about, name='website-about'),
    path('contact', views.contact, name='website-contact'),
    path('base', views.base, name='website-base'),
    path('', views.home, name='website-home'),
]

reservations/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
import datetime


class Reservation(models.Model):
    TIMESLOTS = [
        (0, '09:00'),
        (1, '10:00'),
        (2, '11:00'),
        (3, '12:00'),
        (4, '13:00'),
        (5, '14:00'),
        (6, '15:00'),
        (7, '16:00'),
        (8, '17:00'),
        (9, '18:00'),
        (10, '19:00'),
        (11, '20:00'),
    ]

    COURTS = [
        (0, 'Court 1'),
        (1, 'Court 2'),
        (2, 'Court 3'),
        (3, 'Court 4'),
        (4, 'Court 5'),
        (5, 'Court 6'),
        (6, 'Court 7'),
        (7, 'Court 8'),
        (8, 'Court 9'),
    ]

    title = models.CharField(max_length=200, default='Court Reservation')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    date = models.DateField()
    timeslot = models.IntegerField(choices=TIMESLOTS)
    court_number = models.IntegerField(choices=COURTS)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('reservation-list')

reservations/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django import forms
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    )
from django.urls import reverse_lazy
from .models import Reservation
import datetime


class ReservationListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Reservation
    template_name = 'reservations/reservation_list.html'
    context_object_name = 'reservations'
    ordering = ['-date', 'timeslot']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # ----- Date Search -----
        date_search_input = self.request.GET.get('date-search') or ''
        if date_search_input:
            context['reservations'] = context['reservations'].filter(
                date=date_search_input
            )
        context['date_search_input'] = date_search_input

        # ----- Name Search -----
        name_search_input = self.request.GET.get('name-search') or ''
        if name_search_input:
            context['reservations'] = context['reservations'].filter(
                created_by__last_name__icontains=name_search_input
            )
        context['name_search_input'] = name_search_input

        return context

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False


class ReservationUserListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = 'reservations/reservation_user_list.html'
    context_object_name = 'reservations'
    ordering = ['date', 'timeslot']

    def get_context_data(self, **kwargs):
        today = datetime.date.today()
        context = super().get_context_data(**kwargs)
        context['reservations'] = context['reservations'].filter(
            date__gte=today
        )
        return context


class ReservationDetailView(DetailView):
    model = Reservation


class ReservationCreateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreateView
        ):
    model = Reservation
    fields = ['date', 'timeslot', 'court_number']
    success_url = reverse_lazy('reservation-user-list')
    success_message = (
        'Your reservation has been made successfully. You will'
        ' receive a confirmation email shortly.'
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["reservations"] = Reservation.objects.all()
        return context

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        reservation_date = self.request.POST.get('date')
        reservation_timeslot = self.request.POST.get('timeslot')
        reservation_court_number = self.request.POST.get('court_number')

        if reservation_timeslot == '0':
            reservation_timeslot = '9:00'
        elif reservation_timeslot == '1':
            reservation_timeslot = '10:00'
        elif reservation_timeslot == '2':
            reservation_timeslot = '11:00'
        elif reservation_timeslot == '3':
            reservation_timeslot = '12:00'
        elif reservation_timeslot == '4':
            reservation_timeslot = '13:00'
        elif reservation_timeslot == '5':
            reservation_timeslot = '14:00'
        elif reservation_timeslot == '6':
            reservation_timeslot = '15:00'
        elif reservation_timeslot == '7':
            reservation_timeslot = '16:00'
        elif reservation_timeslot == '8':
            reservation_timeslot = '17:00'
        elif reservation_timeslot == '9':
            reservation_timeslot = '18:00'
        elif reservation_timeslot == '10':
            reservation_timeslot = '19:00'
        elif reservation_timeslot == '11':
            reservation_timeslot = '20:00'

        court_number_correct = (int(reservation_court_number) + 1)

        send_mail(
            'Bushy Park Tennis Club - Reservation Confirmation',  # SUBJECT
            f'Hi {self.request.user.first_name}, \nThis is an email'  # BODY
            f' confirmation of your court reservation at'
            f' Bushy Park Tennis Club. \n\n'
            f'\n -- RESERVATION DETAILS --\n\n'
            f'DATE: {reservation_date}\n'
            f'TIME: {reservation_timeslot} \n'
            f'COURT: {court_number_correct}'
            f'\n\nIf you need to cancel this reservation, please log in'
            f'to your account on our site and click "My Reservations".'
            f'\n\nWe look forward to seeing you at the club!',
            'from@yourdjangoapp.com',  # FROM (OVERRIDDEN)
            [self.request.user.email],  # TO
            fail_silently=False,
        )
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['court_number'].widget = forms.HiddenInput()
        form.fields['date'].widget = forms.HiddenInput()
        return form


class ReservationDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    SuccessMessageMixin,
    DeleteView
        ):
    model = Reservation
    success_url = reverse_lazy('reservation-user-list')
    success_message = (
        'Your reservation has been cancelled.'
    )

    def test_func(self):
        reservation = self.get_object()
        if self.request.user == reservation.created_by:
            return True
        elif self.request.user.is_staff:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(
            ReservationDeleteView, self
            ).delete(request, *args, **kwargs)


@login_required
def date_form(request):
    return render(request, 'reservations/reservation_date.html')

reservations/templates/reservations/reservation_confirm_delete.html
{% extends 'website/base.html' %}
{% block content %}
<!-- RESERVATION DELETION CONFIRMATION PAGE -->
    <div class="mx-5 mt-5" id="reservation-delete-confirm-container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Cancel Reservation</legend>
                <h2 class="my-3">Are you sure you want to cancel this reservation?</h2>
                <p><strong>Cancelling a reservation within 24hrs may incur a cancellation fee</strong></p>
            </fieldset>
            <div class="form-group">
                <!-- DELETES THE RESERVATION -->
                <button class="btn btn-danger" type="submit">Yes, cancel it</button>
                <!-- RETURNS TO RESERVATION DETAILS PAGE -->
                <a class="btn btn-secondary" href="{% url 'reservation-detail' object.id %}">No, go back</a>
            </div>
        </form>
    </div>
{% endblock content %}

reservations/templates/reservations/reservation_date.html
{% extends 'website/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- RESERVATION DATE-FORM PAGE -->
<h1 class="text-center" id="date-form-heading">Court Reservation</h1>
<h2 class="text-center">Use the form below to reserve a court</h2>
<form action="../new/" method="GET" id="dateForm" class="justify-content-center mx-auto mt-5 shadow">
    {% csrf_token %}
    <div class="col-4" id="date-form-container">
        <h3 class="text-center">Please select a date</h3>
        <!-- DATE PICKER -->
        <div id="date-field-container">
            <!-- min and max needed for JS functions -->
            <input class="picker" type="date" name="date" id="date-picker" min='1899-01-01' max='2000-13-13' aria-label="Date picker" required>
        </div>
        <div id="date-button-container">
            <input class="btn btn-outline-info" type="submit" value="Next" id="date-button">
        </div>
    </div>
</form>

{% endblock %}

{% block scripts %}
<!-- JS script to format and pass data to next step of form (reservation_form.html) -->
    <script src="{% static 'js/date.js' %}"></script>
{% endblock scripts %}

reservations/templates/reservations/reservation_detail.html
{% extends 'website/base.html' %}
{% block content %}
<!-- RESERVATION DETAIL PAGE -->
    <article class="mx-5 mt-5" id="reservation-detail-container">
        <h1 class="mt-3">Reservation Details</h1>
        <!-- RESERVATION DETAILS -->
        <div class="media-body">
                <small class="text-muted">Reservation made by: {{ object.created_by.first_name }} {{ object.created_by.last_name }}</small>
                <br>
                <small class="text-muted">Reservation made on {{ object.date_created }}</small>

                <!-- DETAILS TABLE -->
                <table class="table" id="reservation-detail-table">
                    <thead>
                      <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">Date</th>
                        <td>{{ object.date }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Time</th>
                        <td>{{ object.get_timeslot_display }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Court</th>
                        <td>{{ object.get_court_number_display }}</td>
                      </tr>
                    </tbody>
                  </table>
                
                <!-- CHECK IF RESERVATION WAS CREATED BY THIS USER -->
                {% if object.created_by == user %}
                    <div>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'reservation-delete' object.id %}">Cancel Reservation</a>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'reservation-user-list' %}">Back</a>
                    </div>
                <!-- CHECK IF USER IS STAFF (includes superuser) -->
                {% elif user.is_staff %}
                    <div>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'reservation-delete' object.id %}">Cancel Reservation</a>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'reservation-user-list' %}">Back</a>
                    </div>
                {% endif %}
        </div>
    </article>
{% endblock content %}

reservations/templates/reservations/reservation_form.html
{% extends 'website/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!-- RESERVATION-CREATE FORM -->
<!-- Gets the full url text (needed for JS availability check functions) -->
<p id="form-url" hidden>{{ request.get_full_path }}</p>
<h1 class="text-center" id="time-form-heading">Court Reservation</h1>
<h2 class="text-center">Use the form below to reserve a court</h2>
<div class="row justify-content-center mx-auto mt-5">
    <div class="col-4" id="time-form-container">
        <form method="POST">
            {% csrf_token %}
            <!-- Timeslot selector -->
            <h3>Please select a time</h3>
            <div id="time-field-container">
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
            </div>
            <div class="form-group" id="book-button-container">
                <!-- Returns to date selection -->
                <a href="{% url 'reservation-date' %}" class="btn btn-outline-secondary mx-2" ><</a>
                <!-- Creates the reservation -->
                <button class="btn btn-outline-info" id="book-button" type="submit">Book</button>
            </div>
        </form>
    </div>
</div>

<div>
    <!-- Gets all reservations (necessary for JS availability check functions) -->
    {% for reservation in reservations %}
            <p class="reservation-dates" hidden>{{reservation.date|date:'Y-m-d'}}-{{ reservation.timeslot }}-{{ reservation.court_number }}</p>
    {% endfor %}
</div>
{% endblock content %}

{% block scripts %}
<!-- JS script for checking timeslot availability and auto-court selection functionality -->
<script src="{% static 'js/scripts.js' %}"></script>
{% endblock scripts %}

reservations/templates/reservations/reservation_list.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- MASTER RESERVATION LIST -->
    <h1 class="m-4 text-center">Reservations</h1>
    
    <!-- SEARCH BOXES -->
    <div class="my-5" id="reservation-search-container-outer">
        <!-- DATE SEARCH -->
        <div class="mx-3" id="reservation-search-container-date">
            <p class="search-box-header">Search for reservations by date:</p>
            <p>Choose a date below and click search</p>
            <form method="GET">
                <input type="date" name="date-search" value="{{ date_search_input }}" id="reservation-date-search" aria-label="search by date">
                <input type="submit" value="Search">
            </form>
        </div>

        <!-- NAME SEARCH -->
        <div class="mx-3" id="reservation-search-container-name">
            <p class="search-box-header">Search for reservations by name:</p>
            <p>Enter the user's second name and click search</p>
            <form method="GET">
                <input type="text" name="name-search" value="{{ name_search_input }}" id="reservation-name-search" aria-label="search by name">
                <input type="submit" value="Search">
            </form>
        </div>

    </div>

    <!-- RESERVATION TABLE -->
    <div id="reservation-table-container">
        <table class="table table-striped table-hover mx-5" id="reservation-table">
            <thead>
              <tr>
                <th scope="col">Details</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Court</th>
                <th scope="col">Name</th>
              </tr>
            </thead>
            <tbody>
                <!-- AUTO-POPULATES THE TABLE -->
                {% for reservation in reservations %}
                    <tr>
                        <th scope="row"><a href="{% url 'reservation-detail' reservation.id %}">View</a></th>
                        <td>{{ reservation.date }}</td>
                        <td>{{ reservation.get_timeslot_display }}</td>
                        <td>{{ reservation.get_court_number_display }}</td>
                        <td>{{ reservation.created_by.first_name }} {{ reservation.created_by.last_name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
{% endblock content %}

reservations/templates/reservations/reservation_user_list.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- USER RESERVATION LIST -->
    <h1 class="my-5 text-center">Your Upcoming Reservations</h1>
    <h2 class="mx-4 text-center">Click 'View' to see details and/or cancel a reservation</h2>
    <!-- LINK TO CREATE NEW RESERVATION -->
    <p class="text-center">If you would like to make a new reservation, <a class="btn green-button-small" href="{% url 'reservation-date' %}">Click Here</a></p>

    <!-- RESERVATION TABLE -->
    <div id="reservation-table-container">
        <table class="table table-striped table-hover mx-5" id="reservation-table">
            <thead>
              <tr>
                <th scope="col">Details</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Court</th>
                <th scope="col">Name</th>
              </tr>
            </thead>
            <tbody>
                <!-- AUTO-POPULATES RESERVATION TABLE -->
                {% for reservation in reservations %}
                    <!-- ONLY SHOW RESERVATIONS BY THIS USER -->
                    {% if reservation.created_by == user %}
                        <tr>
                            <th scope="row"><a href="{% url 'reservation-detail' reservation.id %}">View</a></th>
                            <td>{{ reservation.date }}</td>
                            <td>{{ reservation.get_timeslot_display }}</td>
                            <td>{{ reservation.get_court_number_display }}</td>
                            <td>{{ reservation.created_by.first_name }} {{ reservation.created_by.last_name }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
          </table>
    </div>
{% endblock content %}